### ISSUE TITLE
minimap-helper command

### ISSUE THREAD

**Issue by clanofartisans** [mousseng/xitools#1]
Just a tiny feature request: Can the `/mmh` command be added back for manual overrides and the current implementation just be "defaults"? I'm still finding myself fiddling with individual zones here and there, especially with HD map packs installed.

If it wasn't working the way you wanted before, don't put a bunch of effort back into it or anything. Super minor request.

Thanks!
-Hugin

**Comment by mousseng** [comment]
fixed in v0.23 (lol)
