### ISSUE TITLE
Using the imgui X button on the Fishe window sets the "Visible" parameter to false.

### ISSUE THREAD

**Issue by tirem** [mousseng/xitools#13]
This seems to be intended behavior on other windows but there is no way to re-enable the visible variable on the Fishe window without going into your settings file.

Possibly unify the Visible and Enabled variables?

**Comment by mousseng** [comment]
`/xit f` or `/xitools fishe` should do it. is that not working?

**Comment by mousseng** [comment]
not having the visible option in config is still an oversight, though
