### ISSUE TITLE
recast (icons)

### ISSUE THREAD

**Issue by FrUct1s** [mousseng/xitools#15]
Thank you so much for porting and imgui-yfying recast :)
Would it be possible to add a spell/ability/trust/wb Icon in front of the name or is that too much work to include?

I love Windower's Timers way of including the icon
![image](https://github.com/mousseng/xitools/assets/58904408/d201391f-e035-4c3a-971e-007810fdad71)

**Comment by mousseng** [comment]
looks like ashita provides the `ListIconId` but i can't see any way to turn that into an icon. alas, i have no experience in actually reading DATs.
