### ISSUE TITLE
Update changed icons

### ISSUE THREAD

**Issue by polishgerbils** [mousseng/xitools#16]
I pulled the latest update and now my "us" has the default icons instead of the new one. Is there something I need to change?

Example of icons on my buff bar that used to be in "us": https://i.imgur.com/MA01tp6.png

What I get after updating: https://i.imgur.com/WROy7xM.png

**Comment by Chibloom** [comment]
v0.18: us: pull icons from game memory in celebration of xipivot being able to redirect the Ashita dat reads. this will probably break if you have malformed icons (like are currently shipped by default in xiview). go to the ashita discord to get the fixed files if that's you

enable the option to redirect ashita's resourcemanager in /pivot if you havent; update xiview if still broken

**Comment by polishgerbils** [comment]
> v0.18: us: pull icons from game memory in celebration of xipivot being able to redirect the Ashita dat reads. this will probably break if you have malformed icons (like are currently shipped by default in xiview). go to the ashita discord to get the fixed files if that's you
> 
> enable the option to redirect ashita's resourcemanager in /pivot if you havent; update xiview dats if still broken

Do you mean this option?

https://i.imgur.com/uANzrOG.png

It unchecks every time i check it. Do you have a link to the "fixed files" you are referencing?
