### ISSUE TITLE
Custom Status Icons Not Loading in "Us"

### ISSUE THREAD

**Issue by PunchWorldwide** [mousseng/xitools#17]
Forgive me if I'm mistaken here but included with xitools is a folder named "icons" that contains the default status icons for the game, which I assumed if replaced would show in place of the default status icons in the "us" partyframes. Unfortunately they do not. If this isn't what that folder is for then you can ignore this. 

Otherwise, I noticed that partybuffs was recently updated because it wasn't showing custom status icons correctly, and since you credit a bit of partybuffs code in the "us" lua I'm wondering if the changes made there could help in this instance.

**Comment by Chibloom** [comment]
us now grabs from current game memory, would need to adjust settings to do it; partybuffs also  always read from game memory, updates wasn't directly related

v0.18: us: pull icons from game memory in celebration of xipivot being able to redirect the Ashita dat reads. this will probably break if you have malformed icons (like are currently shipped by default in xiview). go to the ashita discord to get the fixed files if that's you

enable the option to redirect ashita's resourcemanager in /pivot if you havent; update xiview dats if still broken

**Comment by mousseng** [comment]
ah sorry, i'd forgotten to remove the `icons` folder when i swapped to pulling icons from Ashita.
