### ISSUE TITLE
feature request: xitools-tgt; see target of target for players

### ISSUE THREAD

**Issue by Chibloom** [mousseng/xitools#2]
Ideally something like [targetinfo ](https://github.com/tirem/targetinfo)/ HXUI

**Comment by Chibloom** [comment]
ops i didnt see you already had this planned
`show target and subtarget simultaneously`

**Comment by mousseng** [comment]
added in v0.15. i don't really use this stuff, so let me know if a compact view would be preferable

**Comment by Chibloom** [comment]
oh this actually seems perfect, didnt intend subtarget but that's very helpful for maintaining dots in multiple subtargets without swapping the main target
having a toggle to let sub-target replace main target info could be nice but not necessary, for ppl who get confused over sub-target though (though one could just stack it over the other for now)

my main intention was just for target of target to see who is killing what so can focus on that, which is done fairly well; as relying on <bt> isnt always perfect

**Comment by mousseng** [comment]
cool. i'll probably end up adding a compact mode in the future, but won't prioritize it right now
