### ISSUE TITLE
Unexpected fishe behavior on zoning

### ISSUE THREAD

**Issue by GetAwayCoxn** [mousseng/xitools#22]
Recommend resetting your state var's related to fish on the line information when zoning. Was mid catch on ferry ride when forced zoned by ferry, then warped to lower J homepoint and noticed gui still showing "good feeling" in the window.

![image](https://github.com/mousseng/xitools/assets/66495755/5d91dd4c-f200-4a00-9413-bcc3dcd42540)

**Comment by mousseng** [comment]
good catch. thanks for the report! fixed in v0.24
