### ISSUE TITLE
xitools tgt - target of target causes crash when npcs has no target

### ISSUE THREAD

**Issue by Chibloom** [mousseng/xitools#7]
easily testable on jeuno signet guards
crashes only happen if target of target is on

![image](https://github.com/mousseng/xitools/assets/86545774/c346f91d-a5f6-4805-945c-4bb86bc92518)

**Comment by Chibloom** [comment]
granted target of target doesnt actully work on mobs, could probably restrict to players' targets

**Comment by Chibloom** [comment]
may only be restricted to signet guards actually, target info doesnt display a target of target and xitools doesnt crash when talking to the other npcs in rulude gaderns

**Comment by mousseng** [comment]
this could reasonably happen on any target, but is most likely in town npcs. should be fixed in `v0.15b` though
