### ISSUE TITLE
tgt debuffs not lighting up

### ISSUE THREAD

**Issue by Stori-kun** [mousseng/xitools#9]
TGT works now and it's great! But the text for status under it doesn't light up when debuffs are on. It all stays grey. Maybe I haven't done something? Please let me know.

**Comment by mousseng** [comment]
are you using simplelog? this is generally caused by other addons that block packets (like simplelog)

**Comment by Stori-kun** [comment]
hm.. I actually do not use many addons. I'll check over all the ones I use to see if I can find one that blocks packets

**Comment by Stori-kun** [comment]
THis has been fixed with the newest release! Thank you.

**Comment by Stori-kun** [comment]
Mousseng is the best! Mousseng, is there a way to add a tick counter? For mp resting like WIndower has?
